/*
 *@BEGIN LICENSE
 *@END LICENSE
 */

// Header file automagically generated by CMake. DO NOT TOUCH!
#if !defined(FC_HEADER_INCLUDED)
#define FC_HEADER_INCLUDED

/* Mangling for Fortran global symbols without underscores. */
#define FC_GLOBAL(name,NAME) name##_
//#define FC_GLOBAL(name,NAME) name##

/* Mangling for Fortran global symbols with underscores. */
#define FC_GLOBAL_(name,NAME) name##_
//#define FC_GLOBAL_(name,NAME) name##

#endif
